files:
  - source: /config/locales/client.en.yml
    translation: /config/locales/client.%two_letters_code%.yml
  - source: /config/locales/client.en.yml
    translation: /config/locales/server.%two_letters_code%.yml
