plugins:
  mentionable_items_enabled:
    default: true
    type: bool
    client: true
  mentionable_items_spreadsheet_url:
    default: ''
  mentionable_items_number_of_worksheets:
    default: 1
    max: 5
    min: 1
  mentionable_items_worksheet_max_column:
    default: 10
    min: 4
    max: 30
  mentionable_items_worksheet_max_row:
    default: 200
    min: 20
    max: 1000
  mentionable_items_google_service_account_private_key:
    default: ''
  mentionable_items_google_service_account_email:
    default: ''
