plugins:
  mentionable_items_enabled:
    default: true
    type: bool
  mentionable_items_spreadsheet_name:
    default: ''
  mentionable_items_number_of_worksheets:
    default: 1
    max: 3
    min: 1
  mentionable_items_worksheet_max_column:
    default: 10
    min: 4
    max: 30
  mentionable_items_worksheet_max_row:
    default: 200
    min: 50
    max: 250
  mentionable_items_google_service_account_private_key:
    default: ''
  mentionable_items_google_service_account_email:
    default: ''
