plugins:
  mentionable_items_enabled:
    default: true
    client: true
  mentionable_items_onebox_fallback: true
  mentionable_items_google_spreadsheet_url: ''
  mentionable_items_google_service_account_private_key: ''
  mentionable_items_google_service_account_email: ''
